import { Buffer } from 'node:buffer';
export interface GmailHeader { name?:string|null; value?:string|null }
export interface GmailPart { mimeType?:string|null; body?:{data?:string|null}; parts?:GmailPart[]|null }
export interface GmailPayload extends GmailPart { headers?:GmailHeader[]|null }
export interface NormalizedMessage { providerMessageId:string;providerThreadId:string;internetMessageId:string|null;fromAddress:string;toAddresses:string[];ccAddresses:string[];subject:string;bodyText:string;bodyHtml:string|null;snippet:string;sentAt:Date;hasAttachments:boolean;rawHeaders:Record<string,string> }
const decode=(value:string):string=>Buffer.from(value.replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8');
function collect(part:GmailPart|undefined,texts:string[],htmls:string[]):boolean { if(!part)return false; let attached=Boolean(part.mimeType&&!['text/plain','text/html','multipart/alternative','multipart/mixed','multipart/related'].includes(part.mimeType)); if(part.body?.data){ if(part.mimeType==='text/html')htmls.push(decode(part.body.data)); else if(part.mimeType==='text/plain')texts.push(decode(part.body.data)); } for(const child of part.parts??[]) attached=collect(child,texts,htmls)||attached; return attached; }
const addresses=(value:string|undefined):string[] => (value??'').split(',').map(v=>{const match=/<([^>]+)>/.exec(v); return (match?.[1]??v).trim().toLowerCase();}).filter(Boolean);
export function normalizeGmailMessage(input:{id?:string|null;threadId?:string|null;snippet?:string|null;internalDate?:string|null;payload?:GmailPayload|null}):NormalizedMessage { if(!input.id||!input.threadId) throw new Error('Gmail message lacks IDs'); const headers:Record<string,string>={}; for(const h of input.payload?.headers??[]) if(h.name&&h.value) headers[h.name.toLowerCase()]=h.value; const texts:string[]=[];const htmls:string[]=[];const hasAttachments=collect(input.payload??undefined,texts,htmls); const sentMs=Number(input.internalDate); return {providerMessageId:input.id,providerThreadId:input.threadId,internetMessageId:headers['message-id']??null,fromAddress:addresses(headers.from)[0]??'',toAddresses:addresses(headers.to),ccAddresses:addresses(headers.cc),subject:(headers.subject??'(no subject)').slice(0,998),bodyText:texts.join('\n').slice(0,500_000),bodyHtml:htmls.length?htmls.join('\n').slice(0,1_000_000):null,snippet:(input.snippet??'').slice(0,1000),sentAt:new Date(Number.isFinite(sentMs)?sentMs:Date.now()),hasAttachments,rawHeaders:headers}; }
