import type { FastifyPluginAsync } from 'fastify';
import { z } from 'zod';
import { draftUpdateSchema,policySettingsSchema,success } from '@mailpilot/shared';
import { hashBody } from '../security.js';
import { audit } from '../audit.js';

const idSchema=z.object({id:z.uuid()});
const editAndApproveSchema=draftUpdateSchema.extend({note:z.string().trim().max(1000).optional()});
const knowledgeSchema=z.object({title:z.string().trim().min(1).max(200),content:z.string().trim().min(1).max(100000),tags:z.array(z.string().trim().min(1).max(40)).max(20).default([])});

export const appRoutes:FastifyPluginAsync=async app=>{
  app.addHook('preHandler',app.authenticate);

  app.get('/overview',async(request,reply)=>{const auth=request.authUser;if(!auth)return;const [threads,review,sent,accounts]=await Promise.all([app.services.prisma.emailThread.count({where:{userId:auth.sub}}),app.services.prisma.replyDraft.count({where:{thread:{userId:auth.sub},status:'AWAITING_REVIEW'}}),app.services.prisma.replyDraft.count({where:{thread:{userId:auth.sub},status:'SENT'}}),app.services.prisma.emailAccount.count({where:{userId:auth.sub,status:'ACTIVE'}})]);return reply.send(success({threads,awaitingReview:review,sent,connectedAccounts:accounts}));});
  app.get('/threads',async(request,reply)=>{const auth=request.authUser;if(!auth)return;const rows=await app.services.prisma.emailThread.findMany({where:{userId:auth.sub},orderBy:{lastMessageAt:'desc'},take:100,include:{classifications:{orderBy:{createdAt:'desc'},take:1},drafts:{orderBy:{createdAt:'desc'},take:1}}});return reply.send(success(rows));});
  app.get('/threads/:id',async(request,reply)=>{const auth=request.authUser;if(!auth)return;const params=idSchema.parse(request.params);const row=await app.services.prisma.emailThread.findFirst({where:{id:params.id,userId:auth.sub},include:{messages:{orderBy:{sentAt:'asc'}},classifications:{orderBy:{createdAt:'desc'}},drafts:{include:{critiques:true,reviews:true},orderBy:{createdAt:'desc'}}}});return row?reply.send(success(row)):reply.code(404).send({ok:false,error:{code:'NOT_FOUND',message:'Thread not found'}});});
  app.get('/reviews',async(request,reply)=>{const auth=request.authUser;if(!auth)return;const rows=await app.services.prisma.replyDraft.findMany({where:{thread:{userId:auth.sub},status:'AWAITING_REVIEW'},include:{thread:{include:{messages:{orderBy:{sentAt:'desc'},take:1}}},critiques:{orderBy:{iteration:'desc'},take:1}},orderBy:{createdAt:'asc'}});return reply.send(success(rows));});

  app.put('/drafts/:id',async(request,reply)=>{const auth=request.authUser;if(!auth)return;const params=idSchema.parse(request.params);const input=draftUpdateSchema.parse(request.body);const result=await app.services.prisma.replyDraft.updateMany({where:{id:params.id,thread:{userId:auth.sub},status:{in:['GENERATED','AWAITING_REVIEW']}},data:{...input,version:{increment:1}}});if(!result.count)return reply.code(409).send({ok:false,error:{code:'INVALID_STATE',message:'Draft cannot be edited'}});await audit(app.services.prisma,{userId:auth.sub,action:'DRAFT_EDITED',resourceType:'REPLY_DRAFT',resourceId:params.id,outcome:'SUCCESS'});return reply.send(success({updated:true}));});

  app.post('/drafts/:id/approve',async(request,reply)=>{const auth=request.authUser;if(!auth)return;const params=idSchema.parse(request.params);const approved=await app.services.prisma.$transaction(async tx=>{const draft=await tx.replyDraft.findFirst({where:{id:params.id,thread:{userId:auth.sub},status:'AWAITING_REVIEW'}});if(!draft)return null;const changed=await tx.replyDraft.updateMany({where:{id:draft.id,status:'AWAITING_REVIEW'},data:{status:'APPROVED'}});if(!changed.count)return null;await tx.review.create({data:{draftId:draft.id,reviewerId:auth.sub,decision:'APPROVE',previousBodyHash:hashBody(draft.bodyText),edited:draft.version>1}});return {id:draft.id,version:draft.version};});if(!approved)return reply.code(409).send({ok:false,error:{code:'INVALID_STATE',message:'Draft is not awaiting review'}});await audit(app.services.prisma,{userId:auth.sub,action:'DRAFT_APPROVED',resourceType:'REPLY_DRAFT',resourceId:approved.id,outcome:'SUCCESS'});await app.services.sendQueue.add('send-draft',{draftId:approved.id,userId:auth.sub},{jobId:`send-${approved.id}-${approved.version}`,attempts:5,backoff:{type:'exponential',delay:10000}});return reply.send(success({approved:true}));});

  app.post('/drafts/:id/edit-and-approve',async(request,reply)=>{const auth=request.authUser;if(!auth)return;const params=idSchema.parse(request.params);const input=editAndApproveSchema.parse(request.body);const approved=await app.services.prisma.$transaction(async tx=>{const draft=await tx.replyDraft.findFirst({where:{id:params.id,thread:{userId:auth.sub},status:'AWAITING_REVIEW'}});if(!draft)return null;const changed=await tx.replyDraft.updateMany({where:{id:draft.id,status:'AWAITING_REVIEW'},data:{subject:input.subject,bodyText:input.bodyText,version:{increment:1},status:'APPROVED'}});if(!changed.count)return null;await tx.review.create({data:{draftId:draft.id,reviewerId:auth.sub,decision:'EDIT_AND_APPROVE',previousBodyHash:hashBody(draft.bodyText),edited:true,note:input.note??null}});return {id:draft.id,version:draft.version+1};});if(!approved)return reply.code(409).send({ok:false,error:{code:'INVALID_STATE',message:'Draft is not awaiting review'}});await audit(app.services.prisma,{userId:auth.sub,action:'DRAFT_EDITED_AND_APPROVED',resourceType:'REPLY_DRAFT',resourceId:approved.id,outcome:'SUCCESS'});await app.services.sendQueue.add('send-draft',{draftId:approved.id,userId:auth.sub},{jobId:`send-${approved.id}-${approved.version}`,attempts:5,backoff:{type:'exponential',delay:10000}});return reply.send(success({approved:true,edited:true}));});

  app.post('/drafts/:id/reject',async(request,reply)=>{const auth=request.authUser;if(!auth)return;const params=idSchema.parse(request.params);const rejected=await app.services.prisma.$transaction(async tx=>{const draft=await tx.replyDraft.findFirst({where:{id:params.id,thread:{userId:auth.sub},status:'AWAITING_REVIEW'}});if(!draft)return null;const changed=await tx.replyDraft.updateMany({where:{id:draft.id,status:'AWAITING_REVIEW'},data:{status:'REJECTED'}});if(!changed.count)return null;await tx.review.create({data:{draftId:draft.id,reviewerId:auth.sub,decision:'REJECT',previousBodyHash:hashBody(draft.bodyText),edited:false}});return draft.id;});if(!rejected)return reply.code(409).send({ok:false,error:{code:'INVALID_STATE',message:'Draft is not awaiting review'}});await audit(app.services.prisma,{userId:auth.sub,action:'DRAFT_REJECTED',resourceType:'REPLY_DRAFT',resourceId:rejected,outcome:'SUCCESS'});return reply.send(success({rejected:true}));});

  app.get('/policies',async(request,reply)=>{const auth=request.authUser;if(!auth)return;return reply.send(success(await app.services.prisma.automationPolicy.findMany({where:{userId:auth.sub},orderBy:{priority:'asc'}})));});
  app.put('/policies/:id',async(request,reply)=>{const auth=request.authUser;if(!auth)return;const params=idSchema.parse(request.params);const input=policySettingsSchema.parse(request.body);const result=await app.services.prisma.automationPolicy.updateMany({where:{id:params.id,userId:auth.sub},data:input});if(!result.count)return reply.code(404).send({ok:false,error:{code:'NOT_FOUND',message:'Policy not found'}});await audit(app.services.prisma,{userId:auth.sub,action:'POLICY_UPDATED',resourceType:'AUTOMATION_POLICY',resourceId:params.id,outcome:'SUCCESS'});return reply.send(success({updated:true}));});
  app.get('/audit',async(request,reply)=>{const auth=request.authUser;if(!auth)return;return reply.send(success(await app.services.prisma.auditLog.findMany({where:{userId:auth.sub},orderBy:{createdAt:'desc'},take:200})));});
  app.get('/knowledge',async(request,reply)=>{const auth=request.authUser;if(!auth)return;return reply.send(success(await app.services.prisma.knowledgeItem.findMany({where:{userId:auth.sub},orderBy:{updatedAt:'desc'}})));});
  app.post('/knowledge',async(request,reply)=>{const auth=request.authUser;if(!auth)return;const input=knowledgeSchema.parse(request.body);const item=await app.services.prisma.knowledgeItem.create({data:{userId:auth.sub,...input}});await audit(app.services.prisma,{userId:auth.sub,action:'KNOWLEDGE_CREATED',resourceType:'KNOWLEDGE_ITEM',resourceId:item.id,outcome:'SUCCESS'});return reply.code(201).send(success(item));});
  app.delete('/knowledge/:id',async(request,reply)=>{const auth=request.authUser;if(!auth)return;const params=idSchema.parse(request.params);const result=await app.services.prisma.knowledgeItem.deleteMany({where:{id:params.id,userId:auth.sub}});if(!result.count)return reply.code(404).send({ok:false,error:{code:'NOT_FOUND',message:'Knowledge item not found'}});await audit(app.services.prisma,{userId:auth.sub,action:'KNOWLEDGE_DELETED',resourceType:'KNOWLEDGE_ITEM',resourceId:params.id,outcome:'SUCCESS'});return reply.send(success({deleted:true}));});
  app.get('/analytics',async(request,reply)=>{const auth=request.authUser;if(!auth)return;const grouped=await app.services.prisma.replyDraft.groupBy({by:['status'],where:{thread:{userId:auth.sub}},_count:true});return reply.send(success(grouped));});
};
